name: Tag and create Release

on:
  pull_request:
    types:
      - closed

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    if: startsWith(github.event.pull_request.title, 'Release:') && github.event.pull_request.merged == true
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Git
        run: |
            git config user.name "${{ github.actor }}"
            git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"

      - name: Get version number
        id: get_version_number
        run: |
          echo "Current git branch is: $(git branch --show-current)"
          git pull
          echo "version=v$(cat plugins/quarkus/package.json  | jq .version -r)" >> $GITHUB_OUTPUT

      - name: Tag the commit
        run: |
          release_version=${{ steps.get_version_number.outputs.version }}
          echo "Release version is: $release_version"
          git tag -a "$release_version" -m "Version $release_version"
          git push --follow-tags

      - name: Build Changelog
        uses: mikepenz/release-changelog-builder-action@v4
        id: generate_changelog
        with:
          configurationJson: |
            {
              "template": "#{{CHANGELOG}}\n\n<details>\n<summary>üí¨ Other Changes</summary>\n\n#{{UNCATEGORIZED}}\n</details>",
              "categories": [
                {
                    "title": "## üéâ Exciting New Features",
                    "labels": ["enhancement"]
                },
                {
                    "title": "## üêû Bug Fixes",
                    "labels": ["bug"]
                },
                {
                    "title": "## üì¶ Dependencies",
                    "labels": ["dependencies"]
                }
              ],
              "ignore_labels": [
                "release"
              ]
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: List package URL
        id: list_package_url
        run: |
          PACKAGE_URL=$(find plugins/ -maxdepth 2 -name package.json -exec sh -c "echo -n '  - https://www.npmjs.com/package/' ; cat {} | jq -j '.name' ; echo -n /v/ ; cat {} | jq -j '.version' ; printf '\n'" \;)
          echo "PACKAGE_URL_MD<<EOF" >> $GITHUB_ENV
          echo "$PACKAGE_URL" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version_number.outputs.version }}
          release_name: Release ${{ steps.get_version_number.outputs.version }}
          body: |
            **Release ${{ steps.get_version_number.outputs.version }}**

            ## Changes

            ${{steps.generate_changelog.outputs.changelog}}

            ## npm packages

            ${{ env.PACKAGE_URL_MD }}
          draft: false
          prerelease: false
